spring.application.name=madhavconstruction
server.address=0.0.0.0
server.port=${PORT:8081}




spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/madhavconstruction}
server.servlet.session.cookie.http-only=true
#development
#server.servlet.session.cookie.secure=true

#Deployent
server.servlet.session.cookie.secure=false
server.servlet.session.cookie.same-site=lax
app.cookie.secure=${SESSION_COOKIE_SECURE:false}
app.cookie.same-site=${SESSION_COOKIE_SAME_SITE:Lax}

    
# Disable Spring Security's default login
#spring.security.user.name=${MONGODB_USER}
#spring.security.user.password=${MONGODB_PASSWORD}
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:https://www.madhavconstruction.in,https://madhavconstruction.in/,http://localhost:8000,http://127.0.0.1:8000}
#cors.allowed-origins=http://localhost:8000
