spring.application.name=madhavconstruction
server.address=0.0.0.0
server.port=8081




spring.data.mongodb.uri=mongodb+srv://jaykapadiya6789:Codal%40123@cluster0.rldvzj3.mongodb.net/madhavconstruction?retryWrites=true&w=majority
server.servlet.session.cookie.http-only=true
#development
#server.servlet.session.cookie.secure=true

#Deployent
server.servlet.session.cookie.secure=false
server.servlet.session.cookie.same-site=lax

    
# Disable Spring Security's default login
#spring.security.user.name=${MONGODB_USER}
#spring.security.user.password=${MONGODB_PASSWORD}
cors.allowed-origins=https://www.madhavconstruction.in,https://madhavconstruction.in/
#cors.allowed-origins=http://localhost:8000
